# Some of the most fundamentals concepts about tensors
## Intro

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of the tensor
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of the vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# check the dimension of the matrix
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[5.,6.],[8.,7.],[9.,4.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 6.],
       [8., 7.],
       [9., 4.]], dtype=float16)>

In [9]:
# create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
# check tensor dimension
tensor.ndim

3

In [11]:
# create same tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In case of doubt, create constant tensor

## Creating random tensors

Tensors of arbitrary size which contain random numbers

In [13]:
# Create 2 random but similar tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [14]:
# shuffle the order of elements
not_shuffled = tf.constant([[3,2],[8,6],[4,9]])
# shuffle the tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [4, 9],
       [8, 6]], dtype=int32)>

In [15]:
# shuffle the order of elements with use of seed
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed = 42) # operation level global seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [8, 6],
       [4, 9]], dtype=int32)>

> use both global level and operational level seeds to have shuffled tensors with same order

## other ways to make tensors

In [16]:
# create a tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
# create a tensor of zeros
tf.zeros([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

Main difference between numpy arrays and tensors is that tensors can be run on a GPU (much faster)

In [18]:
# create numpy arrays to tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

## Getting informations from tensors


*   Shape
*   Rank
*   Axis or dimension
*   Size



In [20]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [22]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
# get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print(" Shape of the tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:",rank_4_tensor.shape[0])
print("Elements along last axis:",rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
 Shape of the tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along last axis: 5
Total number of elements: 120


### indexing tensors

tensors can be indexed like python lists

In [24]:
# get the first two elements of each dimension in the tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
# get first element from each dimension for each index except for the final where all elements
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [27]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([[3,4],[8,4]])
rank_2_tensor,rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 4],
        [8, 4]], dtype=int32)>, 2)

In [28]:
# get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>

In [29]:
# add in extra dimension
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[8],
        [4]]], dtype=int32)>

In [30]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[8],
        [4]]], dtype=int32)>

In [31]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 4],
        [8, 4]]], dtype=int32)>

# Manipulating tensors ( tensors operations)

## Basic operations

In [32]:
# add values to a tensor
tensor = tf.constant([[4,6], [8,2]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 16],
       [18, 12]], dtype=int32)>

In [33]:
# original tensor is not changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [8, 2]], dtype=int32)>

In [34]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 60],
       [80, 20]], dtype=int32)>

In [35]:
# substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-6, -4],
       [-2, -8]], dtype=int32)>

In [36]:
# division
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 3.],
       [4., 1.]])>

In [37]:
# tensorflow has built-in functions
tf.multiply(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 80, 120],
       [160,  40]], dtype=int32)>

## Matrix multiplication

2 rules to follow :

1.   inner dimension must match
2.   the resulting matrix has the shape of the outer dimensions



In [38]:
# matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 36],
       [48, 52]], dtype=int32)>

In [39]:
# matrix multiplication with python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 36],
       [48, 52]], dtype=int32)>

In [40]:
# create a tensor (3,2)
X = tf.constant([[1, 2], [3, 4], [5, 6]])
# create another (3,2) tensor
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [42]:
# change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [43]:
# multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [44]:
# multiply reshaped X by Y
tf.reshape(X, shape=(2, 3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [45]:
# compare transpose and reshape
tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [46]:
# matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## dot product

matrix multiplication === dot product

use tf.matmul or tf.tensordot

In [47]:
# perform dotproduct on X and Y with one of them transpose
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [48]:
# perform dotproduct on X and transpose Y
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Usually we transpose rather than reshape when the 2 tensors don't line up

In [53]:
#change datatype of tensor
# create a new tensor with default datatype (float32)
B = tf.constant([1.7,2.6])
B.dtype


tf.float32

In [54]:
C = tf.constant([8,6])
C.dtype

tf.int32

In [55]:
# change from float32 to float16 ( reduced precision)
D = tf.cast(B, dtype=tf.float16)
D


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 2.6], dtype=float16)>

In [57]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8., 6.], dtype=float32)>

## Aggregating Tensors

aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [58]:
# get the absolute values
D = tf.constant([-6, -8])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8], dtype=int32)>

### forms of aggregations:

* get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of a tensor

In [59]:
# create random tensor
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([22, 38, 13,  9, 88, 69, 18, 11,  3,  4, 90, 65, 43, 71, 65, 16, 74,
       66,  3, 89, 36, 16, 96, 92, 29, 44, 80, 16, 23, 79, 73, 99, 78, 84,
       18, 33, 43,  1, 34, 78, 21, 57, 51, 55, 74, 32, 65, 69, 49, 81])>

In [60]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [61]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [62]:
# find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [63]:
# find the mean
tf.reduce_mean(E)


<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [64]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2463>

In [67]:
# find the variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=865>

In [69]:
# find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.412794>